---
title: Meeting Notes
---

We will work as a team to work on meeting notes using Google Docs (*google docs is easier for synchronous collaboration!*).

After the meeting, the final meeting notes will be saved in the [PAM-SI Meeting Repository](https://github.com/SAEL-SWFSC/PAM-SI-Mtg-March2024)

### ***Meeting Notes Exercise***

Practice collaborating on meeting notes The purpose of this exercise is to get everyone involved in developing the meeting notes, and to engage in a few tips and tricks to make this process useful.

1.  Open the [Meeting Notes in Google Docs](https://docs.google.com/document/d/17LR4afSfSn0ChqedIEqsEhJ8r-H_nwMozHPHiBUQ_4I/edit?usp=sharing)

2.  Tips for Team Google Docs

    1.  Newer Information on Top! (so we don't have to scroll and scroll to get to new info!)

    2.  If you like someone else's comment, put a +1 next to it (if there's already a +1, add another! +1 +1 +1)!!!

    3.  Add Links, Screenshots, Emojis, etc

    4.  During sessions, write notes, questions, comments in that section.

    5.  Have a short question, idea, or discussion point, but don't want to interrupt? Put it here! Have an answer? Provide it!

        If it turns out to be worthy of a larger response, then move it to Github Discussions (see more, below)

***Ultimately, we ALL share in meeting notes, so that all ideas, questions, comments, etc are included in the notes.***

### ***Github Discussions***

Use Github Discussions for broad discussions across entire team. Meeting Github Discussions link [here](https://github.com/SAEL-SWFSC/PAM-SI-Mtg-March2024/discussions).

📣 Announcements

💡 Ideas

🗳️ Polls

🙏 Q&A

🙌 Show and Tell
