---
title: List Attendees
---

## List of Attendees Table

***Exercise:*** Insert List of Attendees Table for the Report. Skills include navigating the Meeting Repository (files/folders), working with Quarto visual editor to add a table.

1.  Create a local project for the PAM-SI-Mtg-March2024 Github repository.

    1.  Use Github Desktop to create a local repository

    2.  Create an RStudio Project

2.  View file/folder structure and open Intro file

    1.  Open PAM-SI-Mtg-March2024 project in RStudio

    2.  In lower right hand corner, select 'Files' tab

    3.  Click on the ðŸ“**text** folder to open

    4.  Create a new quarto Document

        1.  Blank File -\> Quarto Doc, Name "**ListAttendees.qmd**"

        2.  Open ListAttendees.qmd and set to Viewer Editor

    5.  Add Table to Intro.qmd

        1.  Insert Table: In Visual Editor, select the Table dropdown menu to insert a table with as many rows as there are attendees, and with 3 columns. Enter "List of Attendees' in the Caption.

        2.  Fill out the table with the names, Affiliations, and Emails for all attendees, like the example below. You can find this information in the 'AttendeesIntros.qmd' file created during the pre-meeting preparation (PAM-SI-Mtg-March2024/AttendeesIntros.qmd)

            | Name           | Affiliation                        | Email                    |
            |----------------|------------------------------------|--------------------------|
            | Shannon Rankin | Southwest Fisheries Science Center | shannon.rankin\@noaa.gov |
            |                |                                    |                          |
            |                |                                    |                          |

    6.  Format **ListAttendees.qmd**

        1.  Place cursor at top of ListAttendees.qmd page, and navigate to Visual Editor tool bar. Using the drop-down menu, change 'Normal' to 'Header 1'.

        2.  Type 'List of Attendees' at top of page.

    7.  Link ListAttendees.qmd to Report

        1.  Open the \_quarto.yaml in the root directory and scroll down to the 'chapters'

        2.  Put the cursor after the index.qmd and hit 'enter' (this will increase the chances that your entry is properly aligned).

        3.  In this position, write '- text/ListAttendees.qmd' (be sure there is only one space between the - and the word 'text')

    8.  Commit & Push to Github

        1.  Open Github Desktop, and in top left corner, use drop-down menu to select 'PAM-SI-Mtg-March2024' repository. Github desktop will identify the changes you made to the document.

        2.  At the bottom left, describe the modifications you made to the document, and then select 'commit'. For example, you may want to write "Add List of Attendees" and in details, state "Added List of Attendees table for Meeting report".

        3.  Once the commit goes through-- select 'Push to Origin' at the top. This will push changes to your Github repository.
