---
title: Workshop Exercises
---

## Github Collaboration

We will create our Workshop Report using our meeting Github Repository (https://github.com/SAEL-SWFSC/PAM-SI-Mtg-March2024){target="_blank"}. By all working together, we can have the bulk of the report completed by the end of the workshop. *Many hands make light work.*

***Exercise:***

We will all work together on one small part of the report to fill in some of the information we know we will need. We will split into pairs and each be assigned an exercise to complete. You will be tagged in your assignment through a Github issue and should receive an associated email. Find your assignment during the Github session either on github.com or through your email, then follow the instructions below.

To ensure that you are working with the most up to date repository, select "Fetch origin" on the top toolbar of Github Desktop before starting the exercise. If at any point you receive an error that you cannot fetch origin or push changes to github, follow the Step 5 of the "Pre Meeting Prep" instructions to login to github.com.

The exercises are:

1.  [Add Introduction Draft Text](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-IntroText.html){target="_blank"}

2.  [Github section](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Github.html){target="_blank"}

3.  [Add Authors](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Authors.html){target="_blank"}

4.  [List of Attendees](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-ListAttendees.html){target="_blank"}

5.  [Acknowledgements Text](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Acknowledge.html){target="_blank"}

6.  [References](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-References.html){target="_blank"}

7.  [NCEI Section](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-NCEI.html){target="_blank"}

8.  [Cloud Section](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Cloud.html){target="_blank"}

9.  [Trend Section](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Climate.html){target="_blank"}

10. [Soundscape Section](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Soundscape.html){target="_blank"}

11. [Stock Assessment Section](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-StockAssess.html){target="_blank"}

12. [Management Section](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Management.html){target="_blank"}

13. [Detection Section](https://sael-swfsc.github.io/OpenScience/content/exercises/PAM-SI-Mtg-Exercises-Detection.html){target="_blank"}

If you are interested in more practice, go to the issues tab on github.com, assign yourself to the Detection Section, and complete that exercise.

At the end of the exercise, make sure everyone saves their changes and pushes their information up to Github, then we will render the output and view the results. How long did it take us to work on that? Continue throughout the workshop, having one or more people draft the paper-- we will work on the google docs linked in the agenda for notes during any given session, but then one person will summarize these notes into Github, and others can edit or revise.
