---
title: Resources
---

Resources for learning more about Open Science

### Open Science

[OpenScapes](https://openscapes.org/)- An organization to facilitate embracing the Open Science movement, including: [resources](https://openscapes.org/resources), [blog](https://openscapes.org/blog), and [Openscapes Approach Guide](https://openscapes.github.io/approach-guide/) (among other things).

[NMFS Open Science](https://nmfs-opensci.github.io/) - Landing page for NMFS Open Science information and resources, including a [Resource Book](https://nmfs-opensci.github.io/ResourceBook/)

[Easing into Open Science](https://online.ucpress.edu/collabra/article/7/1/18684/115927/Easing-Into-Open-Science-A-Guide-for-Graduate)

### Github

[NMFS Github Guide](https://nmfs-opensci.github.io/ResourceBook/)- Information, Best Practices, etc.

[Intro to Github](https://sites.google.com/noaa.gov/nmfs-ost-psaw#h.ummtcilneert)- PSAW presentation by Eli Holmes

[Github Strategies](https://openscapes.github.io/series/core-lessons/github/) (Openscapes)

[Git for Humans](https://www.youtube.com/watch?v=eWxxfttcMts) Intro to Github for non-coders

Installing [GitHub Desktop](https://desktop.github.com/) will install a platform for interacting with GitHub and also Git.

-   Video 1. Setting GitHub Desktop Preferences (2.5 mins) <https://youtu.be/0PVOPL6i3MQ>

-   Video 2. Cloning a repository (2 mins) <https://youtu.be/acIwQO1eOtw>

-   Video 3. Pulling and pushing changes to GitHub (3.5 mins) <https://youtu.be/cQgn3_w27_8>

### Quarto

Video Tutorial: Beautiful reports and presentations with Quarto (RStudio). Link [here](https://youtu.be/hbf7Ai3jnxY).

Quarto [Keynote Presentation](https://openscapes.org/blog/2022-08-10-quarto-keynote/) at RStudio Conference.

[Quarto Tutorial](https://openscapes.github.io/quarto-website-tutorial/) (Openscapes)

### R and Tidyverse

*"You shouldn't feel ashamed about your code- if it solves the problem, it's perfect just the way it is. But also, it could always be better"* Hadley Wickham

[Why Tidy Data?](https://openscapes.org/blog/2020-10-12-tidy-data/)(Openscapes)

[NMFS R User Group](https://nmfs-opensci.github.io/NMFS-R-UG/)

[Big Book of R](https://www.bigbookofr.com/index.html)

[Happy Git with R](https://happygitwithr.com/) (Jenny Bryan)

[Coding Strategies](https://openscapes.github.io/series/core-lessons/coding-strategies.html) (Openscapes)

Name things deliberately (see [3 Rules for Naming Things](https://speakerdeck.com/jennybc/how-to-name-files))
